-- RevenueOS V1: PostgreSQL / Supabase schema. Apply after enabling pgcrypto; pgvector is optional.
create extension if not exists pgcrypto;
do $$ begin create extension if not exists vector; exception when undefined_file then raise notice 'pgvector unavailable; embeddings remain nullable'; end $$;
create type public.agent_status as enum ('active','paused','dead');
create type public.opportunity_stage as enum ('signal','qualified','experimenting','committed','won','lost');
create type public.experiment_status as enum ('queued','running','paused','complete');
create type public.approval_type as enum ('spend','launch','policy');
create type public.approval_status as enum ('pending','approved','declined','expired');
create type public.transaction_direction as enum ('in','out');
create type public.transaction_status as enum ('pending','posted','void');
create table public.workspaces(id uuid primary key default gen_random_uuid(),name text not null,created_at timestamptz not null default now());
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,workspace_id uuid references public.workspaces(id),display_name text,role text not null default 'member' check(role in ('owner','operator','viewer')),created_at timestamptz not null default now());
create table public.agents(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,name text not null,mandate text not null,status public.agent_status not null default 'paused',generation integer not null default 1 check(generation>0),parent_agent_id uuid references public.agents(id),owner_id uuid references public.profiles(id),budget numeric(14,2) not null default 0 check(budget>=0),spent numeric(14,2) not null default 0 check(spent>=0),revenue numeric(14,2) not null default 0 check(revenue>=0),survival_score smallint check(survival_score between 0 and 100),thesis text,last_heartbeat_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(workspace_id,name,generation));
create table public.agent_heartbeats(id uuid primary key default gen_random_uuid(),agent_id uuid not null references public.agents(id) on delete cascade,payload jsonb not null default '{}',created_at timestamptz not null default now());
create table public.opportunities(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,agent_id uuid references public.agents(id) on delete set null,title text not null,segment text,stage public.opportunity_stage not null default 'signal',value numeric(14,2) not null check(value>=0),probability numeric(5,4) not null check(probability between 0 and 1),confidence numeric(5,4) not null check(confidence between 0 and 1),effort smallint not null check(effort between 1 and 6),risk text not null check(risk in ('low','medium','high')),owner_id uuid references public.profiles(id),summary text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.experiments(id uuid primary key default gen_random_uuid(),opportunity_id uuid not null references public.opportunities(id) on delete cascade,name text not null,status public.experiment_status not null default 'queued',metric text not null,target text not null,progress smallint not null default 0 check(progress between 0 and 100),spend numeric(14,2) not null default 0 check(spend>=0),verdict text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.approvals(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,agent_id uuid references public.agents(id) on delete set null,type public.approval_type not null,status public.approval_status not null default 'pending',title text not null,amount numeric(14,2) check(amount>=0),request jsonb not null default '{}',requested_by uuid references public.profiles(id),decided_by uuid references public.profiles(id),decided_at timestamptz,created_at timestamptz not null default now());
create table public.transactions(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,agent_id uuid references public.agents(id) on delete set null,occurred_at timestamptz not null default now(),description text not null,category text not null,amount numeric(14,2) not null check(amount>=0),direction public.transaction_direction not null,status public.transaction_status not null default 'pending',external_reference text unique,created_at timestamptz not null default now());
create table public.knowledge(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,title text not null,body text not null,source text not null,tag text,confidence numeric(5,4) check(confidence between 0 and 1),metadata jsonb not null default '{}',embedding jsonb,created_at timestamptz not null default now());
create table public.events(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,agent_id uuid references public.agents(id) on delete set null,event_type text not null,actor text not null,detail jsonb not null default '{}',created_at timestamptz not null default now());
create table public.agent_rules(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,name text not null,enabled boolean not null default true,config jsonb not null default '{}',created_at timestamptz not null default now());
create index agents_workspace_status_idx on public.agents(workspace_id,status); create index opportunities_workspace_stage_idx on public.opportunities(workspace_id,stage); create index experiments_opportunity_idx on public.experiments(opportunity_id); create index approvals_workspace_status_idx on public.approvals(workspace_id,status); create index transactions_workspace_occurred_idx on public.transactions(workspace_id,occurred_at desc); create index knowledge_workspace_created_idx on public.knowledge(workspace_id,created_at desc); create index events_workspace_created_idx on public.events(workspace_id,created_at desc);
comment on column public.knowledge.embedding is 'Optional embedding fallback as JSON. When pgvector is enabled, migrate this column to vector(1536) and add an ivfflat/hnsw index.';
alter table public.workspaces enable row level security; alter table public.profiles enable row level security; alter table public.agents enable row level security; alter table public.agent_heartbeats enable row level security; alter table public.opportunities enable row level security; alter table public.experiments enable row level security; alter table public.approvals enable row level security; alter table public.transactions enable row level security; alter table public.knowledge enable row level security; alter table public.events enable row level security; alter table public.agent_rules enable row level security;
-- RLS preparation: policies intentionally require workspace membership; service-role jobs bypass RLS only server-side.
create policy workspace_members_agents on public.agents for all using (workspace_id in (select workspace_id from public.profiles where id=auth.uid())) with check (workspace_id in (select workspace_id from public.profiles where id=auth.uid()));
-- Add equivalent workspace membership policies for remaining tables before production client access.
